### ISSUE TITLE
Target accuracy and hyperparamteres

### ISSUE THREAD

**Issue by undertherain** [sparticlesteve/cosmoflow-benchmark#17]
Hi!
I started from the https://github.com/mlperf-hpc/mlperf-hpc
and could not trace any path which would lead to specification of training target (value and the metric itself) as well as constraints on hyperparameters
Should not it be included with the each benchamrk?

**Comment by sparticlesteve** [comment]
Hello,

Sorry for the delayed reply. I didn't see a notification for this issue for some reason.

That readme links to the latest rules docs for hpc: https://github.com/mlperf-hpc/mlperf-hpc#rules
It's there that we give the quality targets, and (for now) link to a hyperparameter table. We do however need to move the hyperparameter table into the rules doc itself, and will try to get to that soon.

Thanks,
Steve
